# Generated by Django 5.2.5 on 2025-09-16 10:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicost', '0002_gallery_created_at_gallery_location_gallery_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedetail',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
